version: '3'
services:
  bancodedados:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - 3306:3306

  app:
    build: ./php
    ports:
      - 8080:80
