version: '3'
services:
  bancodedados:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/var/lib/mysql/

  app:
    build: ./php/
    ports:
      - 8080:80
    volumes:
      - ./app/:/var/www/html 


